// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-mDKrQ5T1dBx2lZp038fRmX8AEgU4Jko',
    appId: '1:586726449700:web:06935f258e84a7ae216eb1',
    messagingSenderId: '586726449700',
    projectId: 'travellog-4fe94',
    authDomain: 'travellog-4fe94.firebaseapp.com',
    storageBucket: 'travellog-4fe94.firebasestorage.app',
    measurementId: 'G-TK9SJ6BPXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoq06Yi_w29BZ6F31hiec2BFa5XigSD8c',
    appId: '1:586726449700:android:69f51e743bb76bb7216eb1',
    messagingSenderId: '586726449700',
    projectId: 'travellog-4fe94',
    storageBucket: 'travellog-4fe94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUFcwd2E-rlyLiRjJsiHDqYiZWstdxOE',
    appId: '1:586726449700:ios:10cf1c2305e52017216eb1',
    messagingSenderId: '586726449700',
    projectId: 'travellog-4fe94',
    storageBucket: 'travellog-4fe94.firebasestorage.app',
    androidClientId: '586726449700-vn3uskag7os7t1su7nh0oaduvgoloigk.apps.googleusercontent.com',
    iosClientId: '586726449700-4tjfhjm7nfabsn2jdo842ug8tkeurgf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.travellog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUFcwd2E-rlyLiRjJsiHDqYiZWstdxOE',
    appId: '1:586726449700:ios:10cf1c2305e52017216eb1',
    messagingSenderId: '586726449700',
    projectId: 'travellog-4fe94',
    storageBucket: 'travellog-4fe94.firebasestorage.app',
    androidClientId: '586726449700-vn3uskag7os7t1su7nh0oaduvgoloigk.apps.googleusercontent.com',
    iosClientId: '586726449700-4tjfhjm7nfabsn2jdo842ug8tkeurgf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.travellog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-mDKrQ5T1dBx2lZp038fRmX8AEgU4Jko',
    appId: '1:586726449700:web:d15915693583d04e216eb1',
    messagingSenderId: '586726449700',
    projectId: 'travellog-4fe94',
    authDomain: 'travellog-4fe94.firebaseapp.com',
    storageBucket: 'travellog-4fe94.firebasestorage.app',
    measurementId: 'G-39PBH33YQN',
  );

}